#!/bin/bash

echo -n "Do you want to publish a new release of LuaOs [y/n]: ";
read response
echo ""

if [ "$response" == "y" ]; then
	version=`sed '33q;d' main/whitecat.h | cut -d '"' -f 2`
	build=`sed '4q;d' main/build.h`

	filename="LuaOS-$version-$build.hex"
	filename=${filename/ /-}

	echo "This release will be publish with this file name: $filename"
	echo ""

	echo -n "Continue [y/n?]: ";
	read response

	if [ "$response" == "y" ]; then
		echo $filename > releases/current
		cp -f LuaOS_V1.hex releases/$filename
	else
	        if [ "$response" != "n" ]; then
        	        echo "Invalid response";
        	fi
	fi

	exit;
fi

if [ "$response" != "n" ]; then
	echo "Invalid response";
fi
